### ISSUE TITLE
Write a script to pull the contribution data updates in future quarters

### ISSUE THREAD

**Issue by skirmer** [skirmer/ILGov2018#10]
Jay!

**Comment by skirmer** [comment]
Or Andrew?

**Comment by jayqi** [comment]
Work in progress: https://github.com/jayqi/ILGov2018/blob/dev/scripts/pull_receipts_data.R

Remaining issue is that there is a limit to 1000 results by default. I think the best solution is to paginate and I'm going to update the script to do that.
